enum WeatherCondition {
  sunny,
  partlyCloudy,
  cloudy,
  overcast,
  mist,
  patchyRainPossible,
  patchySnowPossible,
  patchySleetPossible,
  patchyFreezingDrizzlePossible,
  thunderyOutbreaksPossible,
  blowingSnow,
  blizzard,
  fog,
  freezingFog,
  patchyLightDrizzle,
  lightDrizzle,
  freezingDrizzle,
  heavyFreezingDrizzle,
  patchyLightRain,
  lightRain,
  moderateRainAtTimes,
  moderateRain,
  heavyRainAtTimes,
  heavyRain,
  lightFreezingRain,
  moderateOrHeavyFreezingRain,
  lightSleet,
  moderateOrHeavySleet,
  patchyLightSnow,
  lightSnow,
  patchyModerateSnow,
  moderateSnow,
  patchyHeavySnow,
  heavySnow,
  icePellets,
  lightRainShower,
  moderateOrHeavyRainShower,
  torrentialRainShower,
  lightSleetShowers,
  moderateOrHeavySleetShowers,
  lightSnowShowers,
  moderateOrHeavySnowShowers,
  lightShowersOfIcePellets,
  moderateOrHeavyShowersOfIcePellets,
  patchyLightRainWithThunder,
  moderateOrHeavyRainWithThunder,
  patchyLightSnowWithThunder,
  moderateOrHeavySnowWithThunder,
}

Map<int, WeatherCondition> codeToWeatherCondition = {
  1000: WeatherCondition.sunny,
  1003: WeatherCondition.partlyCloudy,
  1006: WeatherCondition.cloudy,
  1009: WeatherCondition.overcast,
  1030: WeatherCondition.mist,
  1063: WeatherCondition.patchyRainPossible,
  1066: WeatherCondition.patchySnowPossible,
  1069: WeatherCondition.patchySleetPossible,
  1072: WeatherCondition.patchyFreezingDrizzlePossible,
  1087: WeatherCondition.thunderyOutbreaksPossible,
  1114: WeatherCondition.blowingSnow,
  1117: WeatherCondition.blizzard,
  1135: WeatherCondition.fog,
  1147: WeatherCondition.freezingFog,
  1150: WeatherCondition.patchyLightDrizzle,
  1153: WeatherCondition.lightDrizzle,
  1168: WeatherCondition.freezingDrizzle,
  1171: WeatherCondition.heavyFreezingDrizzle,
  1180: WeatherCondition.patchyLightRain,
  1183: WeatherCondition.lightRain,
  1186: WeatherCondition.moderateRainAtTimes,
  1189: WeatherCondition.moderateRain,
  1192: WeatherCondition.heavyRainAtTimes,
  1195: WeatherCondition.heavyRain,
  1198: WeatherCondition.lightFreezingRain,
  1201: WeatherCondition.moderateOrHeavyFreezingRain,
  1204: WeatherCondition.lightSleet,
  1207: WeatherCondition.moderateOrHeavySleet,
  1210: WeatherCondition.patchyLightSnow,
  1213: WeatherCondition.lightSnow,
  1216: WeatherCondition.patchyModerateSnow,
  1219: WeatherCondition.moderateSnow,
  1222: WeatherCondition.patchyHeavySnow,
  1225: WeatherCondition.heavySnow,
  1237: WeatherCondition.icePellets,
  1240: WeatherCondition.lightRainShower,
  1243: WeatherCondition.moderateOrHeavyRainShower,
  1246: WeatherCondition.torrentialRainShower,
  1249: WeatherCondition.lightSleetShowers,
  1252: WeatherCondition.moderateOrHeavySleetShowers,
  1255: WeatherCondition.lightSnowShowers,
  1258: WeatherCondition.moderateOrHeavySnowShowers,
  1261: WeatherCondition.lightShowersOfIcePellets,
  1264: WeatherCondition.moderateOrHeavyShowersOfIcePellets,
  1273: WeatherCondition.patchyLightRainWithThunder,
  1276: WeatherCondition.moderateOrHeavyRainWithThunder,
  1279: WeatherCondition.patchyLightSnowWithThunder,
  1282: WeatherCondition.moderateOrHeavySnowWithThunder
};
