enum WeatherCondition {
  sunny,
  partly_cloudy,
  cloudy,
  overcast,
  mist,
  patchy_rain_possible,
  patchy_snow_possible,
  patchy_sleet_possible,
  patchy_freezing_drizzle_possible,
  thundery_outbreaks_possible,
  blowing_snow,
  blizzard,
  fog,
  freezing_fog,
  patchy_light_drizzle,
  light_drizzle,
  freezing_drizzle,
  heavy_freezing_drizzle,
  patchy_light_rain,
  light_rain,
  moderate_rain_at_times,
  moderate_rain,
  heavy_rain_at_times,
  heavy_rain,
  light_freezing_rain,
  moderate_or_heavy_freezing_rain,
  light_sleet,
  moderate_or_heavy_sleet,
  patchy_light_snow,
  light_snow,
  patchy_moderate_snow,
  moderate_snow,
  patchy_heavy_snow,
  heavy_snow,
  ice_pellets,
  light_rain_shower,
  moderate_or_heavy_rain_shower,
  torrential_rain_shower,
  light_sleet_showers,
  moderate_or_heavy_sleet_showers,
  light_snow_showers,
  moderate_or_heavy_snow_showers,
  light_showers_of_ice_pellets,
  moderate_or_heavy_showers_of_ice_pellets,
  patchy_light_rain_with_thunder,
  moderate_or_heavy_rain_with_thunder,
  patchy_light_snow_with_thunder,
  moderate_or_heavy_snow_with_thunder,
}

Map<int, WeatherCondition> codeToWeatherCondition = {
  1000: WeatherCondition.sunny,
  1003: WeatherCondition.partly_cloudy,
  1006: WeatherCondition.cloudy,
  1009: WeatherCondition.overcast,
  1030: WeatherCondition.mist,
  1063: WeatherCondition.patchy_rain_possible,
  1066: WeatherCondition.patchy_snow_possible,
  1069: WeatherCondition.patchy_sleet_possible,
  1072: WeatherCondition.patchy_freezing_drizzle_possible,
  1087: WeatherCondition.thundery_outbreaks_possible,
  1114: WeatherCondition.blowing_snow,
  1117: WeatherCondition.blizzard,
  1135: WeatherCondition.fog,
  1147: WeatherCondition.freezing_fog,
  1150: WeatherCondition.patchy_light_drizzle,
  1153: WeatherCondition.light_drizzle,
  1168: WeatherCondition.freezing_drizzle,
  1171: WeatherCondition.heavy_freezing_drizzle,
  1180: WeatherCondition.patchy_light_rain,
  1183: WeatherCondition.light_rain,
  1186: WeatherCondition.moderate_rain_at_times,
  1189: WeatherCondition.moderate_rain,
  1192: WeatherCondition.heavy_rain_at_times,
  1195: WeatherCondition.heavy_rain,
  1198: WeatherCondition.light_freezing_rain,
  1201: WeatherCondition.moderate_or_heavy_freezing_rain,
  1204: WeatherCondition.light_sleet,
  1207: WeatherCondition.moderate_or_heavy_sleet,
  1210: WeatherCondition.patchy_light_snow,
  1213: WeatherCondition.light_snow,
  1216: WeatherCondition.patchy_moderate_snow,
  1219: WeatherCondition.moderate_snow,
  1222: WeatherCondition.patchy_heavy_snow,
  1225: WeatherCondition.heavy_snow,
  1237: WeatherCondition.ice_pellets,
  1240: WeatherCondition.light_rain_shower,
  1243: WeatherCondition.moderate_or_heavy_rain_shower,
  1246: WeatherCondition.torrential_rain_shower,
  1249: WeatherCondition.light_sleet_showers,
  1252: WeatherCondition.moderate_or_heavy_sleet_showers,
  1255: WeatherCondition.light_snow_showers,
  1258: WeatherCondition.moderate_or_heavy_snow_showers,
  1261: WeatherCondition.light_showers_of_ice_pellets,
  1264: WeatherCondition.moderate_or_heavy_showers_of_ice_pellets,
  1273: WeatherCondition.patchy_light_rain_with_thunder,
  1276: WeatherCondition.moderate_or_heavy_rain_with_thunder,
  1279: WeatherCondition.patchy_light_snow_with_thunder,
  1282: WeatherCondition.moderate_or_heavy_snow_with_thunder,
};
